name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bhrashtachar-mukt-backend
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          source: ./backend
          region: us-central1 # Change to your preferred region
          env_vars: |
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          flags: --allow-unauthenticated